// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "avtk_test.h"

AvtkTest::AvtkTest() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(495, 415);
    w = o;
    o->user_data((void*)(this));
    { button = new AvtkButton(75, 247, 100, 63, "label");
      button->box(FL_NO_BOX);
      button->color(FL_BACKGROUND_COLOR);
      button->selection_color(FL_BACKGROUND_COLOR);
      button->labeltype(FL_NORMAL_LABEL);
      button->labelfont(0);
      button->labelsize(14);
      button->labelcolor(FL_FOREGROUND_COLOR);
      button->align(Fl_Align(FL_ALIGN_CENTER));
      button->when(FL_WHEN_RELEASE);
    } // AvtkButton* button
    o->end();
  } // Fl_Double_Window* o
  w->show();
}
