// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef avtk_test_h
#define avtk_test_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "avtk_button.h"

class AvtkTest {
public:
  AvtkTest();
  AvtkButton *button;
};
#endif
