// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "avtk_test.h"

AvtkTest::AvtkTest() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(495, 415, "Avtk Showcase");
    w = o;
    o->user_data((void*)(this));
    { bg = new AvtkBackground(200, 12, 135, 178, "background");
      bg->box(FL_NO_BOX);
      bg->color(FL_BACKGROUND_COLOR);
      bg->selection_color(FL_BACKGROUND_COLOR);
      bg->labeltype(FL_NORMAL_LABEL);
      bg->labelfont(0);
      bg->labelsize(14);
      bg->labelcolor(FL_FOREGROUND_COLOR);
      bg->align(Fl_Align(FL_ALIGN_CENTER));
      bg->when(FL_WHEN_RELEASE);
    } // AvtkBackground* bg
    { highButtn = new AvtkButton(10, 49, 100, 31, "label");
      highButtn->box(FL_NO_BOX);
      highButtn->color(FL_BACKGROUND_COLOR);
      highButtn->selection_color(FL_BACKGROUND_COLOR);
      highButtn->labeltype(FL_NORMAL_LABEL);
      highButtn->labelfont(0);
      highButtn->labelsize(14);
      highButtn->labelcolor(FL_FOREGROUND_COLOR);
      highButtn->align(Fl_Align(FL_ALIGN_CENTER));
      highButtn->when(FL_WHEN_RELEASE);
    } // AvtkButton* highButtn
    { lowButtn = new AvtkButton(10, 13, 100, 31, "label");
      lowButtn->box(FL_NO_BOX);
      lowButtn->color(FL_BACKGROUND_COLOR);
      lowButtn->selection_color(FL_BACKGROUND_COLOR);
      lowButtn->labeltype(FL_NORMAL_LABEL);
      lowButtn->labelfont(0);
      lowButtn->labelsize(14);
      lowButtn->labelcolor(FL_FOREGROUND_COLOR);
      lowButtn->align(Fl_Align(FL_ALIGN_CENTER));
      lowButtn->when(FL_WHEN_RELEASE);
    } // AvtkButton* lowButtn
    { dial_high = new AvtkDial(120, 10, 35, 30);
      dial_high->box(FL_OVAL_BOX);
      dial_high->color(FL_BACKGROUND_COLOR);
      dial_high->selection_color(FL_INACTIVE_COLOR);
      dial_high->labeltype(FL_NORMAL_LABEL);
      dial_high->labelfont(0);
      dial_high->labelsize(14);
      dial_high->labelcolor(FL_FOREGROUND_COLOR);
      dial_high->align(Fl_Align(FL_ALIGN_BOTTOM));
      dial_high->when(FL_WHEN_CHANGED);
    } // AvtkDial* dial_high
    { dial_low = new AvtkDial(255, 85, 35, 30, "testing");
      dial_low->box(FL_OVAL_BOX);
      dial_low->color(FL_BACKGROUND_COLOR);
      dial_low->selection_color(FL_INACTIVE_COLOR);
      dial_low->labeltype(FL_NORMAL_LABEL);
      dial_low->labelfont(0);
      dial_low->labelsize(14);
      dial_low->labelcolor(FL_FOREGROUND_COLOR);
      dial_low->align(Fl_Align(FL_ALIGN_BOTTOM));
      dial_low->when(FL_WHEN_CHANGED);
    } // AvtkDial* dial_low
    o->end();
  } // Fl_Double_Window* o
  w->show();
}
